# ========================================================================
# TEST: SolarPanelEngine
# ========================================================================
# Automated tests generated by EVE Genesis
# Run with: pytest test_solar_panel_engine.py -v
# ========================================================================

import pytest
from datetime import datetime
from solar_panel_engine import (
    SolarPanelEngine, 
    SolarPanelResult, 
    PanelStatus,
    get_solar_engine
)


class TestSolarPanelEngineInit:
    """Test initialization."""
    
    def test_init_default(self):
        """Test default initialization."""
        engine = SolarPanelEngine()
        assert engine.panel_capacity == 400.0
        assert engine.VERSION == "1.0.0"
    
    def test_init_custom(self):
        """Test custom initialization."""
        engine = SolarPanelEngine(
            panel_capacity_wp=500,
            voltage_mpp=40.0,
            current_mpp=12.5,
            panel_id="TEST-001"
        )
        assert engine.panel_capacity == 500
        assert engine.panel_id == "TEST-001"
    
    def test_singleton(self):
        """Test singleton accessor."""
        engine1 = get_solar_engine()
        engine2 = get_solar_engine()
        assert engine1 is engine2


class TestProcessReading:
    """Test reading processing."""
    
    @pytest.fixture
    def engine(self):
        return SolarPanelEngine(panel_capacity_wp=400)
    
    def test_process_valid_reading(self, engine):
        """Test processing a valid reading."""
        result = engine.process_reading(
            voltage=38.0,
            current=10.0,
            temperature=35.0,
            irradiance=900
        )
        
        assert result.success is True
        assert result.data["power_w"] == 380.0
        assert result.data["voltage_v"] == 38.0
        assert result.data["current_a"] == 10.0
        assert "efficiency" in result.data
        assert "status" in result.data
    
    def test_process_without_irradiance(self, engine):
        """Test that irradiance is estimated when not provided."""
        result = engine.process_reading(
            voltage=38.0,
            current=10.0,
            temperature=30.0
        )
        
        assert result.success is True
        assert result.data["power_w"] == 380.0
    
    def test_process_zero_values(self, engine):
        """Test processing zero values."""
        result = engine.process_reading(
            voltage=0,
            current=0,
            temperature=25.0,
            irradiance=0
        )
        
        assert result.success is True
        assert result.data["power_w"] == 0.0
    
    def test_shading_detection(self, engine):
        """Test that shading is detected."""
        # Low power with high irradiance = shading
        result = engine.process_reading(
            voltage=20.0,
            current=2.0,
            temperature=30.0,
            irradiance=800
        )
        
        assert result.success is True
        # Should have warnings about efficiency
        assert len(result.warnings) > 0 or result.data["status"] in ["shaded", "degraded"]


class TestMPPT:
    """Test MPPT functionality."""
    
    @pytest.fixture
    def engine(self):
        return SolarPanelEngine(
            panel_capacity_wp=400,
            voltage_mpp=38.0,
            current_mpp=10.5
        )
    
    def test_mppt_recommendation_no_data(self, engine):
        """Test MPPT with no readings."""
        result = engine.get_mppt_recommendation()
        assert result.success is False
    
    def test_mppt_recommendation_with_data(self, engine):
        """Test MPPT after processing readings."""
        # Process a reading first
        engine.process_reading(38.0, 10.0, 35.0, 900)
        
        result = engine.get_mppt_recommendation()
        assert result.success is True
        assert "recommended_voltage" in result.data
        assert "recommended_current" in result.data
        assert "expected_power" in result.data
    
    def test_mppt_temperature_adjustment(self, engine):
        """Test that MPPT adjusts for temperature."""
        # Cold conditions
        engine.process_reading(38.0, 10.0, 15.0, 900)
        cold_mppt = engine.get_mppt_recommendation()
        
        # Reset and test hot conditions
        engine2 = SolarPanelEngine(voltage_mpp=38.0, current_mpp=10.5)
        engine2.process_reading(38.0, 10.0, 55.0, 900)
        hot_mppt = engine2.get_mppt_recommendation()
        
        # Hot should have lower voltage recommendation
        assert hot_mppt.data["recommended_voltage"] < cold_mppt.data["recommended_voltage"]


class TestDailyProduction:
    """Test daily production calculation."""
    
    @pytest.fixture
    def engine(self):
        return SolarPanelEngine()
    
    def test_daily_production_no_readings(self, engine):
        """Test with no readings."""
        result = engine.get_daily_production()
        assert result.success is True
        assert result.data["kwh"] == 0.0
    
    def test_daily_production_with_readings(self, engine):
        """Test with multiple readings."""
        # Add several readings
        for i in range(10):
            engine.process_reading(
                voltage=37.0 + i * 0.1,
                current=9.5 + i * 0.05,
                temperature=30.0,
                irradiance=800
            )
        
        result = engine.get_daily_production()
        assert result.success is True
        assert result.data["readings"] == 10
        assert "peak_w" in result.data


class TestEdgeCases:
    """Test edge cases and error handling."""
    
    def test_negative_values(self):
        """Test handling of negative values."""
        engine = SolarPanelEngine()
        result = engine.process_reading(
            voltage=-10.0,
            current=-5.0,
            temperature=25.0
        )
        # Should handle gracefully
        assert result.success is True
    
    def test_extreme_temperature(self):
        """Test extreme temperature handling."""
        engine = SolarPanelEngine()
        result = engine.process_reading(
            voltage=35.0,
            current=8.0,
            temperature=85.0,  # Very hot
            irradiance=1000
        )
        
        assert result.success is True
        # Should have temperature warning
        assert len(result.warnings) > 0
    
    def test_history_limiting(self):
        """Test that history is limited."""
        engine = SolarPanelEngine()
        
        # Add many readings
        for i in range(1500):
            engine.process_reading(38.0, 10.0, 30.0, 800)
        
        # Should be limited to 1000
        assert len(engine._readings) <= 1000


# ========================================================================
# RUN TESTS
# ========================================================================

if __name__ == "__main__":
    print("=" * 60)
    print("RUNNING TESTS: SolarPanelEngine")
    print("=" * 60)
    
    # Quick manual test run
    engine = SolarPanelEngine(panel_id="TEST")
    
    # Test 1
    result = engine.process_reading(38.0, 10.0, 35.0, 900)
    assert result.success, "Process reading failed"
    print("✅ Test 1: Process reading")
    
    # Test 2
    mppt = engine.get_mppt_recommendation()
    assert mppt.success, "MPPT recommendation failed"
    print("✅ Test 2: MPPT recommendation")
    
    # Test 3
    daily = engine.get_daily_production()
    assert daily.success, "Daily production failed"
    print("✅ Test 3: Daily production")
    
    print("\n✅ All manual tests passed!")
    print("\nFor full test suite, run: pytest test_solar_panel_engine.py -v")
